DROP TABLE IF EXISTS historicos;
CREATE TABLE IF NOT EXISTS historicos (
    id INT AUTO_INCREMENT PRIMARY KEY, -- Alterado de SERIAL para INT AUTO_INCREMENT
    date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data TEXT NOT NULL
);